export enum LOOP_STATE {
  NO_LOOP = 'NO_LOOP',
  ALL_LOOP = 'ALL_LOOP',
  ONE_LOOP = 'ONE_LOOP',
}

export const NEXT_LOOP_STATE = {
  [LOOP_STATE.NO_LOOP]: LOOP_STATE.ALL_LOOP,
  [LOOP_STATE.ALL_LOOP]: LOOP_STATE.ONE_LOOP,
  [LOOP_STATE.ONE_LOOP]: LOOP_STATE.NO_LOOP,
};
